### ISSUE TITLE
How agent achieve micro-level operations

### ISSUE THREAD

**Issue by eadstry** [histmeisah/Large-Language-Models-play-StarCraftII#1]
I noticed that in the operational space there are only macro actions like building units. How can agent achieve more  micro-level operations , such as commanding units to go to a specific coordinate for combat?

**Comment by histmeisah** [comment]
Our method focuses on macro action and game strategy. So in the micro-level ,we use human-designed some simple scripts(dont like these AI:https://www.youtube.com/@ProBotsAI). Actually, our agent cant use any clear command such as attack some units or move to some specific place.
