### ISSUE TITLE
Evaluation Metrics 计算脚本

### ISSUE THREAD

**Issue by Akon-Fiber** [histmeisah/Large-Language-Models-play-StarCraftII#16]
你好，我想请问是否可以提供Population Block Ratio (PBR)、Resource Utilization Ratio (RUR)、Average Population Utilization (APU)的计算脚本？

**Comment by histmeisah** [comment]
已经更新了,在这里:
sc2_rl_agent/starcraftenv_test/git_evaluation_metrics.py
使用的时候注意,由于直接写的时候不知道怎么直接读取sc2 replay,我是这直接读取的log文件.所以你得按照注释,将log日志进行处理.

**Comment by Akon-Fiber** [comment]
十分感谢您的回复，我这边计算时有点不一样的地方：resource计算total_minerals 时，我采用了score.py脚本中的self.state.score.spent_minerals游戏中消耗矿产量，您这边是将raw_observation.json中的mineral累加，我不确定我计算的是否跟你这边计算的有出入

**Comment by histmeisah** [comment]
主要还是看胜率,这些指标是辅助筛选用的.
具体的计算方式有出入也没关系,看起来你的可能还更好一点.
如果你有更好的计算方法也可以加进来,这些指标的核心理念就是衡量LLM agent的宏观运营能力,只要体现这个就行.

**Comment by Akon-Fiber** [comment]
是的，很感谢贵团队的开源与回复，我们这边也是想在胜率的基础之上，添加更多辅助指标，用于分析不同LLM在具体能力上的差异

**Comment by histmeisah** [comment]
如果有什么问题也可以加我联系方式:
qq:740988193
微信:Histmeisah

**Comment by Akon-Fiber** [comment]
好的，感谢
