### ISSUE TITLE
My map file path is clearly correct, why will report an error, can not find the file

### ISSUE THREAD

**Issue by a1wj1** [histmeisah/Large-Language-Models-play-StarCraftII#23]
![0240e2c3fa1fbbb95ea1b0126cfa326](https://github.com/user-attachments/assets/7982549a-3342-4fd1-b775-e67a5d6881fd)

![2fa635dc4793f626060d6896da78f66](https://github.com/user-attachments/assets/9ad71fb9-062b-4b08-8b29-279614542a1f)

**Comment by histmeisah** [comment]
maybe you can test some example code of python-sc2 or my rule-base code.

I guess the main reason is system environment variables. You can search on the github or ask for LLMs
