### ISSUE TITLE
api key and api url

### ISSUE THREAD

**Issue by xizai123** [histmeisah/Large-Language-Models-play-StarCraftII#3]
i want to know how can i get my api key and my api base url

**Comment by histmeisah** [comment]
Now google have released their LLM gemini-pro, a free llm.
you can add the gemini_test in LLM folder like gpt_test.py  and swap the related python file such as /summarize/gpt_test  and  and add agent/gemini_agent. We have test glm4,gemini-pro and claude2, they all have good performance in our setting.

Here is gemini-pro`s link:https://deepmind.google/technologies/gemini/#build-with-gemini

**Comment by xizai123** [comment]
sorry to bother you again,when i run test_the_env.py,my sc2 starts up for a few seconds and then shuts down automatically,below are error reported:
`action_dict {'TRAIN UNIT': {0: 'TRAIN PROBE', 1: 'TRAIN ZEALOT', 2: 'TRAIN ADEPT', 3: 'TRAIN STALKER', 4: 'TRAIN SENTRY', 5: 'TRAIN HIGHTEMPLAR', 6: 'TRAIN DARKTEMPLAR', 7: 'TRAIN VOIDRAY', 8: 'TRAIN CARRIER', 9: 'TRAIN TEMPEST', 10: 'TRAIN ORACLE', 11: 'TRAIN PHOENIX', 12: 'TRAIN MOTHERSHIP', 13: 'TRAIN OBSERVER', 14: 'TRAIN IMMORTAL', 15: 'TRAIN WARPPRISM', 16: 'TRAIN COLOSSUS', 17: 'TRAIN DISRUPTOR', 18: 'MORPH ARCHON'}, 'BUILD STRUCTURE': {19: 'BUILD PYLON', 20: 'BUILD ASSIMILATOR', 21: 'BUILD NEXUS', 22: 'BUILD GATEWAY', 23: 'BUILD CYBERNETICSCORE', 24: 'BUILD FORGE', 25: 'BUILD TWILIGHTCOUNCIL', 26: 'BUILD ROBOTICSFACILITY', 27: 'BUILD STARGATE', 28: 'BUILD TEMPLARARCHIVE', 29: 'BUILD DARKSHRINE', 30: 'BUILD ROBOTICSBAY', 31: 'BUILD FLEETBEACON', 32: 'BUILD PHOTONCANNON', 33: 'BUILD SHIELDBATTERY'}, 'RESEARCH TECHNIQUE': {34: 'RESEARCH WARPGATERESEARCH', 35: 'RESEARCH PROTOSSAIRWEAPONSLEVEL1', 36: 'RESEARCH PROTOSSAIRWEAPONSLEVEL2', 37: 'RESEARCH PROTOSSAIRWEAPONSLEVEL3', 38: 'RESEARCH PROTOSSAIRARMORSLEVEL1', 39: 'RESEARCH PROTOSSAIRARMORSLEVEL2', 40: 'RESEARCH PROTOSSAIRARMORSLEVEL3', 41: 'RESEARCH ADEPTPIERCINGATTACK', 42: 'RESEARCH BLINKTECH', 43: 'RESEARCH CHARGE', 44: 'RESEARCH PROTOSSGROUNDWEAPONSLEVEL1', 45: 'RESEARCH PROTOSSGROUNDWEAPONSLEVEL2', 46: 'RESEARCH PROTOSSGROUNDWEAPONSLEVEL3', 47: 'RESEARCH PROTOSSGROUNDARMORSLEVEL1', 48: 'RESEARCH PROTOSSGROUNDARMORSLEVEL2', 49: 'RESEARCH PROTOSSGROUNDARMORSLEVEL3', 50: 'RESEARCH PROTOSSSHIELDSLEVEL1', 51: 'RESEARCH PROTOSSSHIELDSLEVEL2', 52: 'RESEARCH PROTOSSSHIELDSLEVEL3', 53: 'RESEARCH 
EXTENDEDTHERMALLANCE', 54: 'RESEARCH GRAVITICDRIVE', 55: 'RESEARCH OBSERVERGRAVITICBOOSTER', 56: 'RESEARCH PSISTORMTECH', 57: 'RESEARCH VOIDRAYSPEEDUPGRADE', 58: 'RESEARCH PHOENIXRANGEUPGRADE', 59: 'RESEARCH TEMPESTGROUNDATTACKUPGRADE'}, 'OTHER ACTION': {60: 'SCOUTING PROBE', 61: 'SCOUTING OBSERVER', 62: 'SCOUTING ZEALOT', 63: 'SCOUTING PHOENIX', 64: 'MULTI-ATTACK', 65: 'MULTI-RETREAT', 66: 'CHRONOBOOST NEXUS', 67: 'CHRONOBOOST CYBERNETICSCORE', 
68: 'CHRONOBOOST TWILIGHTCOUNCIL', 69: 'CHRONOBOOST STARGATE', 70: 'CHRONOBOOST FORGE', 71: 'EMPTY ACTION'}}
model_path_hf c:\Users\23675\Large-Language-Models-play-StarCraftII-main\config\material\models\embedding\sentence-transformers_all-mpnet-base-v2
2024-01-31 16:12:46.559 | INFO     | sc2.protocol:_execute:72 - Client status changed to Status.launched (was None)
2024-01-31 16:12:46.561 | INFO     | sc2.controller:create_game:37 - Creating new game
2024-01-31 16:12:46.562 | INFO     | sc2.controller:create_game:38 - Map:     Ancient Cistern LE
2024-01-31 16:12:46.563 | INFO     | sc2.controller:create_game:39 - Players: Bot Protoss_Bot(Protoss), Computer Hard(Zerg, RandomBuild)
2024-01-31 16:12:46.565 | INFO     | sc2.protocol:_execute:72 - Client status changed to Status.init_game (was Status.launched)
2024-01-31 16:12:53.408 | INFO     | sc2.protocol:_execute:72 - Client status changed to Status.in_game (was None)
2024-01-31 16:12:53.411 | INFO     | sc2.main:_play_game:221 - Player 1 - Bot Protoss_Bot(Protoss)
Defend: False
action None
Traceback (most recent call last):
  File "C:\Users\23675\AppData\Local\anaconda3\envs\sc_demo3\lib\site-packages\urllib3\connection.py", line 203, in _new_conn
    sock = connection.create_connection(
  File "C:\Users\23675\AppData\Local\anaconda3\envs\sc_demo3\lib\site-packages\urllib3\util\connection.py", line 85, in create_connection
    raise err
  File "C:\Users\23675\AppData\Local\anaconda3\envs\sc_demo3\lib\site-packages\urllib3\util\connection.py", line 73, in create_connection
    sock.connect(sa)
TimeoutError: [WinError 10060] 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。`

i am wondering did I not set the api key and api url correctly in test_the_env.py?

**Comment by histmeisah** [comment]
This error maybe caused by `protobuf`  version. You can reinstall burnysc2 and test again.
Due to our demo this developed on python-sc2, you can first test your env in python-sc2 demo：https://github.com/BurnySc2/python-sc2.
And if you still have promblem, you can sent your contact information  to my email address: histmeisah@foxmail.com
