### ISSUE TITLE
environment deploy problem of requirements.txt

### ISSUE THREAD

**Issue by GavinWz** [histmeisah/Large-Language-Models-play-StarCraftII#9]
![image](https://github.com/histmeisah/Large-Language-Models-play-StarCraftII/assets/49334529/deef49a0-46a5-4c61-841f-5f6d2dbb6223)
The requirements.txt file may be a conda requirements, but in README file you use pip install. And it recommends us to use “conda create -n sc2 --file requirements.txt” to install requirements in this txt file, but large number of these requirements cannot be found.

**Comment by histmeisah** [comment]
Well, I think you might need to manually reinstall the relevant packages.
